
   // Práctica 2, ej2. AUTORES: Fernando Pastor Peralta (897113) Fabrizio Bryan Duarte Jáuregui (736857)
    
%%
.
[\n]
^(casa|cas.?|casa.|(ca.?|cas.|(c.?|ca.|(.?|c.|.c)a)s)a|(ca.?|cas.|(c.?|ca.|(.?|c.|.c)a)s).?|(cas.?|casa.|(ca.?|cas.|(c.?|ca.|(.?|c.|.c)a)s)a).|((c.?|ca.|(.?|c.|.c)a).?|(ca.?|cas.|(c.?|ca.|(.?|c.|.c)a)s).|((.?|c.|.c).?|(c.?|ca.|(.?|c.|.c)a).|(..?|(.?|c.|.c).|.c)a)s)a)$ printf("%s\n", yytext);
%%
