// default_handlers.c — ISRs débiles por defecto para que enlace
__weak void Default_IRQHandler(void) {}

#define DH(name) __weak void name(void) { Default_IRQHandler(); }

DH(CCM_AAR_IRQHandler)
DH(COMP_LPCOMP_IRQHandler)
DH(CRYPTOCELL_IRQHandler)
DH(ECB_IRQHandler)
DH(FPU_IRQHandler)
DH(GPIOTE_IRQHandler)
DH(I2S_IRQHandler)
DH(MWU_IRQHandler)
DH(NFCT_IRQHandler)
DH(PDM_IRQHandler)
DH(POWER_CLOCK_IRQHandler)
DH(PWM0_IRQHandler)
DH(PWM1_IRQHandler)
DH(PWM2_IRQHandler)
DH(PWM3_IRQHandler)
DH(QDEC_IRQHandler)
DH(QSPI_IRQHandler)
DH(RADIO_IRQHandler)
DH(RNG_IRQHandler)
DH(RTC0_IRQHandler)
DH(RTC1_IRQHandler)
DH(RTC2_IRQHandler)
DH(SAADC_IRQHandler)
DH(SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler)
DH(SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler)
DH(SPIM2_SPIS2_SPI2_IRQHandler)
DH(SPIM3_IRQHandler)
DH(SWI0_EGU0_IRQHandler)
DH(SWI1_EGU1_IRQHandler)
DH(SWI2_EGU2_IRQHandler)
DH(SWI3_EGU3_IRQHandler)
DH(SWI4_EGU4_IRQHandler)
DH(SWI5_EGU5_IRQHandler)
DH(TEMP_IRQHandler)
DH(TIMER0_IRQHandler)
DH(TIMER1_IRQHandler)
DH(TIMER2_IRQHandler)
DH(TIMER3_IRQHandler)
DH(TIMER4_IRQHandler)
DH(UARTE0_UART0_IRQHandler)
DH(UARTE1_IRQHandler)
DH(USBD_IRQHandler)
DH(WDT_IRQHandler)
